logging:
  level: INFO
  appenders:
      - type: console
      - type: file
        currentLogFilename: ./logs.log
        archivedLogFilenamePattern: ./logs-%d.log.gz
        archivedFileCount: 5
        timeZone: UTC
server:
  rootPath: /api/
  requestLog:
      appenders:
        - type: console
  applicationConnectors:
    - type: http
      port: 5000
  adminConnectors:
    - type: http
      port: 5005

authDomain: appraisal-grenoble-bourji.auth0.com
kid: NTFDOEQwNTU4OTg1QTNCMzYxOERCQTU5QjRERDlDMDdBNzg4NUZDQw

database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: gemappcon_p
  password: yxj1j4hc
  url: jdbc:mysql://west2-mysql-instance-appcon.ccb8nbtr8ua4.us-west-2.rds.amazonaws.com:3306/DFS?autoConnect=true
  properties:
    charset: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQLDialect
  validationQuery: select ITEM from TEST
  logValidationErrors: true
  checkConnectionOnConnect: true
  checkConnectionOnBorrow: true
  checkConnectionOnReturn: true
  validationQueryTimeout: 5s
  maxWaitForConnection: 3s
  minSize: 5
  maxSize: 20
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute

email:
  username: appraisal.confidence@gmail.com
  password: cAmMChK2rvLvCqtH